version: '3.8'

volumes:
  mysql-volume:

services:
  app:
    build:
      context: .
      # m1用のDockerfile参照
      dockerfile: ./docker/php/m1/Dockerfile
    volumes:
      - ./src/:/app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    container_name: app_m1

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - app
    volumes:
      - ./src/:/app
    container_name: web_m1

  db:
    image: mysql:8.0
    platform: linux/x86_64
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    container_name: db_m1

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"