version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        USERNAME: ${USERNAME}
        GROUPNAME: ${GROUPNAME}
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./src/:/app

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - app
    volumes:
      - ./src/:/app
