@startwbs
'https://plantuml.com/wbs-diagram

* WebERP
** ホーム
*** 受注管理
**** 手持ちの案件
**** 受注内容追加ボタン
*** 工数管理
**** 今日のタスク
**** 作業時間入力ボタン
***** 開始
***** 終了
*** 入金管理
**** 納品済みで未入金一覧
** ダッシュボード
*** 今日のタスク
*** 月当たりの売り上げ
*** 月の稼働時間(8時間*平日を1とした円グラフ)
*** 年間総受注数
*** 年間総売り上げ
** 受注管理
*** 受注内容追加
*** 受注内容編集
*** 受注内容確認
**** 案件名
**** 誰から
**** 納期
**** 内容
**** 金額
*** 金額の把握(確定申告)
**** 年間総売り上げ
**** 税金
** 工数管理
*** 作業にかけた時間を管理
**** 年間の作業時間
**** 月の作業時間
**** 自分の力量の把握
**** 振り返り
*** コードレビュー
** 入金管理
*** 現状の確認
**** 見積もり書
**** 納品書
**** 請求書
**** 入金確認
** アカウント管理
*** アカウント削除
*** ログアウト
*** メアド変更
*** パス変更
@endwbs