@startmindmap
'https://plantuml.com/mindmap-diagram

caption CoopTech
title WebERP Idea

* やりたいこと
** コメント
*** 誰が、誰に、コメントする。
*** @でユーザにメンションできるようにしたい
*** "#"で案件情報にメンションできるようにしたい

** 見積管理
*** いくらで見積もりしたか
*** 失注したか？
**** 失注した理由を分析したい

** 受注管理
*** 誰経由で案件もらったか
*** どんな案件か
*** 過去の案件からの派生か
*** どの見積もりを受注したか(見積もりとの連携)

** 売上管理
*** どの受注に対する売上か(受注との連携)
*** 年度、月度の売上表示

** 請求管理
*** 誰にいくらで請求したか(売上との連携)
*** 納付される日はいつか
*** 請求した金額は納付されたか

** 仕入管理
*** 仕入そもそもあるの？
*** 個人事業主なら経費で、とか？

** 勤怠管理
*** いつからいつまでどの案件に関わったのか？

** ユーザ管理
*** ユーザの招待
*** ユーザの権限変更

** マイクロサービス化
*** ユーザがどのアプリを使うか管理する
*** cooptech というアカウント -> 管理者として登録者を作成
**** そのアカウントに紐づくユーザが管理されているアプリケーションを使用できる
*** メインサービスで使用するサービスの登録を行う
*** 収益化を仮定して各サービスの月額利用を想定
**** 1アプリにつき月額500円など

@endmindmap

