@startwbs
'https://plantuml.com/wbs-diagram

* WebERP

** 見積管理
*** 見積一覧 (/estimate)
**** 見積登録 (/estimate/create)
**** 見積修正 (/estimate/edit)
***** 見積書発行 (/estimate/issue-quotation)
**** 見積詳細(/estimate/show)

** ホーム
*** 受注管理
**** 現在受注しているもの
**** 納期

*** 売上管理
**** 見積・納品・請求書作成
*** 交流
**** 新着コメント

** マスタ管理
*** 顧客マスタ
*** テンプレートマスタ

** 受注管理
*** 受注一覧
**** 誰から
**** 内容
**** 納期
**** 金額
*** 未受注一覧
**** 分析用コメント欄
*** 完成したものへのリンク

** 工数管理
*** 案件に関わった期間
*** 納期までの期間(視覚化)
*** コード共有(共有と連携)
**** コードレビュー

** 売上管理
*** 見積書・納品書・請求書作成
*** 仕入れ？経費？計算
*** 売り上げ一覧
*** 確定申告の有無

** ダッシュボード
*** 現在の受注内容一覧
*** 現在の売り上げ
*** 未入金一覧
*** 案件対応期間(横の棒グラフ)

** 交流
*** コードレビュー
*** 未受注分析へのコメント

** 管理者ページ
*** メンバーの招待
*** 企業管理
*** ログアウト
@endwbs