@startwbs
'https://plantuml.com/wbs-diagram

* WebERP

** ホーム
*** 受注管理
**** 現在受注しているもの
**** 納期
*** 売上管理
**** 見積・納品・請求書作成

** 受注管理
*** 受注一覧
**** 誰から
**** 内容
**** 納期
**** 金額
*** 未受注一覧
**** 分析用コメント欄
*** 完成したものへのリンク

** 工数管理
*** 案件に関わった期間
*** 納期までの期間(視覚化)
*** コード共有(共有と連携)
**** コードレビュー

** 売上管理
*** 見積書・納品書・請求書作成
*** 仕入れ？経費？計算
*** 売り上げ一覧
*** 税金計算

** ダッシュボード
*** 現在の受注内容一覧
*** 現在の売り上げ
*** 未入金一覧
*** 案件対応期間(横の棒グラフ)

** 共有(他者に見られるページ)
*** コードレビュー
*** 未受注分析へのコメント
*** アカウント共有(フォロー)

** アカウント管理
*** 共有の許可
*** ログアウト
*** フォロワー管理
*** フォロワーの共有画面に遷移